[package]
name = "player"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "player"
path = "lib.rs"

[dependencies]
common = { path = "../Common/" }
